# Generated by Django 5.2.8 on 2026-03-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tracker', '0002_alter_smsnotification_status_graderecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_profiles', to='tracker.student'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('sysadmin', 'System Administrator')], default='teacher', max_length=20),
        ),
    ]
